author: &author Canberra Girls' Programming Network
title: *author
email: canberragpn@gmail.com
description: The Canberra branch of GPN Australia
baseurl: ''
github: http://github.com/canberragpn
imgdir: /static/img
logo: gpn-square-yellow.png

menu-items:
    - text: Home
      url: /
    - text: Events
      url: /events/
      layout: post
    - text: Register
      url: /register/
    - text: Workshops
      url: /workshops/
    - text: Contact
      url: /contact/

sass:
  style: compressed

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
